name: Build FanqieDL
on:
  push:
    branches: [master]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt update && sudo apt install -y libssl-dev pkg-config libboost-all-dev
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: fanqie-dl-linux
          path: target/release/fanqie-dl
